# Generated by Django 5.0 on 2023-12-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('Cse(Regular)', 'CSE(R)'), ('CSE(Honors)', 'CSE(H)'), ('CS&IT', 'CSIT')], max_length=20),
        ),
    ]
