# Generated by Django 5.0 on 2023-12-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_faculty_department_alter_faculty_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='contact',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='facultyid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
